# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque}
  s.version = "1.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Wanstrath"]
  s.date = %q{2010-03-15}
  s.description = %q{}
  s.email = %q{chris@ozmm.org}
  s.executables = ["resque", "resque-web"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "bin/resque",
     "bin/resque-web",
     "lib/resque.rb",
     "lib/resque/errors.rb",
     "lib/resque/failure.rb",
     "lib/resque/failure/base.rb",
     "lib/resque/failure/hoptoad.rb",
     "lib/resque/failure/multiple.rb",
     "lib/resque/failure/queue_per_error.rb",
     "lib/resque/failure/redis.rb",
     "lib/resque/helpers.rb",
     "lib/resque/job.rb",
     "lib/resque/queue_set.rb",
     "lib/resque/server.rb",
     "lib/resque/server/public/csp.js",
     "lib/resque/server/public/delete.png",
     "lib/resque/server/public/idle.png",
     "lib/resque/server/public/jquery-1.4a1.js",
     "lib/resque/server/public/jquery.event.drag-1.5.js",
     "lib/resque/server/public/jquery.event.drop-1.2.js",
     "lib/resque/server/public/jquery.relatize_date.js",
     "lib/resque/server/public/jsio/buffer.js",
     "lib/resque/server/public/jsio/csp/client.js",
     "lib/resque/server/public/jsio/csp/errors.js",
     "lib/resque/server/public/jsio/csp/transports.js",
     "lib/resque/server/public/jsio/env.js",
     "lib/resque/server/public/jsio/env/browser/csp.js",
     "lib/resque/server/public/jsio/env/browser/networkConsole.html",
     "lib/resque/server/public/jsio/env/browser/orbited.js",
     "lib/resque/server/public/jsio/env/browser/postmessage.js",
     "lib/resque/server/public/jsio/env/browser/tcp.js",
     "lib/resque/server/public/jsio/env/node/csp.js",
     "lib/resque/server/public/jsio/env/node/csp/proxy.js",
     "lib/resque/server/public/jsio/env/node/csp/server.js",
     "lib/resque/server/public/jsio/env/node/csp/util.js",
     "lib/resque/server/public/jsio/env/node/tcp.js",
     "lib/resque/server/public/jsio/interfaces.js",
     "lib/resque/server/public/jsio/jsio.js",
     "lib/resque/server/public/jsio/later.js",
     "lib/resque/server/public/jsio/logging.js",
     "lib/resque/server/public/jsio/protocols/buffered.js",
     "lib/resque/server/public/jsio/protocols/delimited.js",
     "lib/resque/server/public/jsio/protocols/echo.js",
     "lib/resque/server/public/jsio/protocols/rtjp.js",
     "lib/resque/server/public/jsio/protocols/stomp.js",
     "lib/resque/server/public/jsio/std/base64.js",
     "lib/resque/server/public/jsio/std/uri.js",
     "lib/resque/server/public/jsio/std/utf8.js",
     "lib/resque/server/public/jsio/std/uuid.js",
     "lib/resque/server/public/jsio/util/browser.js",
     "lib/resque/server/public/jsio/util/sizzle.js",
     "lib/resque/server/public/jsio/util/sprintf.js",
     "lib/resque/server/public/logo.psd",
     "lib/resque/server/public/poll.png",
     "lib/resque/server/public/ranger.js",
     "lib/resque/server/public/sort.png",
     "lib/resque/server/public/sort_queues.js",
     "lib/resque/server/public/start.png",
     "lib/resque/server/public/stop.png",
     "lib/resque/server/public/style.css",
     "lib/resque/server/public/working.png",
     "lib/resque/server/views/concurrency.haml",
     "lib/resque/server/views/error.haml",
     "lib/resque/server/views/failed.haml",
     "lib/resque/server/views/key.haml",
     "lib/resque/server/views/layout.haml",
     "lib/resque/server/views/next_more.haml",
     "lib/resque/server/views/overview.haml",
     "lib/resque/server/views/queues.haml",
     "lib/resque/server/views/screen.sass",
     "lib/resque/server/views/stats.haml",
     "lib/resque/server/views/workers.haml",
     "lib/resque/server/views/working.haml",
     "lib/resque/stat.rb",
     "lib/resque/tasks.rb",
     "lib/resque/version.rb",
     "lib/resque/worker.rb",
     "tasks/redis.rake",
     "tasks/resque.rake"
  ]
  s.homepage = %q{http://github.com/defunkt/resque}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{}
  s.test_files = [
    "test/resque_test.rb",
     "test/test_helper.rb",
     "test/worker_test.rb",
     "examples/async_helper.rb",
     "examples/demo/app.rb",
     "examples/demo/job.rb",
     "examples/instance.rb",
     "examples/simple.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<redis-namespace>, [">= 0"])
      s.add_runtime_dependency(%q<vegas>, [">= 0.1.2"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_runtime_dependency(%q<compass>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<redis-namespace>, [">= 0"])
      s.add_dependency(%q<vegas>, [">= 0.1.2"])
      s.add_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_dependency(%q<compass>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<redis-namespace>, [">= 0"])
    s.add_dependency(%q<vegas>, [">= 0.1.2"])
    s.add_dependency(%q<sinatra>, [">= 0.9.2"])
    s.add_dependency(%q<compass>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

