# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque}
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Wanstrath"]
  s.date = %q{2010-02-28}
  s.description = %q{}
  s.email = %q{chris@ozmm.org}
  s.executables = ["resque", "resque-pool", "resque-pool-list", "resque-web"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "CONTRIBUTORS",
     "HISTORY.md",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/resque",
     "bin/resque-pool",
     "bin/resque-pool-list",
     "bin/resque-web",
     "config.ru",
     "deps.rip",
     "examples/async_helper.rb",
     "examples/demo/README.markdown",
     "examples/demo/Rakefile",
     "examples/demo/app.rb",
     "examples/demo/config.ru",
     "examples/demo/job.rb",
     "examples/god/resque.god",
     "examples/god/stale.god",
     "examples/instance.rb",
     "examples/simple.rb",
     "init.rb",
     "lib/resque.rb",
     "lib/resque/errors.rb",
     "lib/resque/failure.rb",
     "lib/resque/failure/base.rb",
     "lib/resque/failure/hoptoad.rb",
     "lib/resque/failure/multiple.rb",
     "lib/resque/failure/queue_per_error.rb",
     "lib/resque/failure/redis.rb",
     "lib/resque/helpers.rb",
     "lib/resque/job.rb",
     "lib/resque/pool.rb",
     "lib/resque/pool/peer.rb",
     "lib/resque/queue_set.rb",
     "lib/resque/server.rb",
     "lib/resque/server/public/csp.js",
     "lib/resque/server/public/delete.png",
     "lib/resque/server/public/idle.png",
     "lib/resque/server/public/jquery-1.4a1.js",
     "lib/resque/server/public/jquery.event.drag-1.5.js",
     "lib/resque/server/public/jquery.event.drop-1.2.js",
     "lib/resque/server/public/jquery.relatize_date.js",
     "lib/resque/server/public/jsio/buffer.js",
     "lib/resque/server/public/jsio/csp/client.js",
     "lib/resque/server/public/jsio/csp/errors.js",
     "lib/resque/server/public/jsio/csp/transports.js",
     "lib/resque/server/public/jsio/env.js",
     "lib/resque/server/public/jsio/env/browser/csp.js",
     "lib/resque/server/public/jsio/env/browser/networkConsole.html",
     "lib/resque/server/public/jsio/env/browser/orbited.js",
     "lib/resque/server/public/jsio/env/browser/postmessage.js",
     "lib/resque/server/public/jsio/env/browser/tcp.js",
     "lib/resque/server/public/jsio/env/node/csp.js",
     "lib/resque/server/public/jsio/env/node/csp/proxy.js",
     "lib/resque/server/public/jsio/env/node/csp/server.js",
     "lib/resque/server/public/jsio/env/node/csp/util.js",
     "lib/resque/server/public/jsio/env/node/tcp.js",
     "lib/resque/server/public/jsio/interfaces.js",
     "lib/resque/server/public/jsio/jsio.js",
     "lib/resque/server/public/jsio/later.js",
     "lib/resque/server/public/jsio/logging.js",
     "lib/resque/server/public/jsio/protocols/buffered.js",
     "lib/resque/server/public/jsio/protocols/delimited.js",
     "lib/resque/server/public/jsio/protocols/echo.js",
     "lib/resque/server/public/jsio/protocols/rtjp.js",
     "lib/resque/server/public/jsio/protocols/stomp.js",
     "lib/resque/server/public/jsio/std/base64.js",
     "lib/resque/server/public/jsio/std/uri.js",
     "lib/resque/server/public/jsio/std/utf8.js",
     "lib/resque/server/public/jsio/std/uuid.js",
     "lib/resque/server/public/jsio/util/browser.js",
     "lib/resque/server/public/jsio/util/sizzle.js",
     "lib/resque/server/public/jsio/util/sprintf.js",
     "lib/resque/server/public/logo.psd",
     "lib/resque/server/public/poll.png",
     "lib/resque/server/public/ranger.js",
     "lib/resque/server/public/sort.png",
     "lib/resque/server/public/sort_queues.js",
     "lib/resque/server/public/start.png",
     "lib/resque/server/public/stop.png",
     "lib/resque/server/public/style.css",
     "lib/resque/server/public/working.png",
     "lib/resque/server/views/concurrency.haml",
     "lib/resque/server/views/error.haml",
     "lib/resque/server/views/failed.haml",
     "lib/resque/server/views/key.haml",
     "lib/resque/server/views/layout.haml",
     "lib/resque/server/views/next_more.haml",
     "lib/resque/server/views/overview.haml",
     "lib/resque/server/views/pool.haml",
     "lib/resque/server/views/pool_table.haml",
     "lib/resque/server/views/queues.haml",
     "lib/resque/server/views/screen.sass",
     "lib/resque/server/views/stats.haml",
     "lib/resque/server/views/workers.haml",
     "lib/resque/server/views/working.haml",
     "lib/resque/stat.rb",
     "lib/resque/tasks.rb",
     "lib/resque/version.rb",
     "lib/resque/worker.rb",
     "pkg/resque-1.1.0.gem",
     "pkg/resque-1.4.0.gem",
     "resque.gemspec",
     "resque2.rb",
     "samples/animator.rb",
     "samples/bezier_playground.rb",
     "samples/circle_collision.rb",
     "samples/fern.rb",
     "samples/flight_patterns.rb",
     "samples/full_screen.rb",
     "samples/getting_started.rb",
     "samples/jwishy.rb",
     "samples/orbit.rb",
     "samples/pong.rb",
     "samples/processing_app/3D/camera/ortho_vs_perspective.rb",
     "samples/processing_app/3D/camera/perspective.rb",
     "samples/processing_app/3D/form/brick_tower.rb",
     "samples/processing_app/3D/typography/data/Univers66.vlw.gz",
     "samples/processing_app/3D/typography/kinetic_type.rb",
     "samples/processing_app/ABOUT",
     "samples/processing_app/basics/arrays/array.rb",
     "samples/processing_app/basics/arrays/array_2d.rb",
     "samples/processing_app/basics/arrays/array_objects.rb",
     "samples/processing_app/basics/color/brightness.rb",
     "samples/processing_app/basics/color/color_wheel.rb",
     "samples/processing_app/basics/color/creating.rb",
     "samples/processing_app/basics/color/hue.rb",
     "samples/processing_app/basics/color/linear_gradient.rb",
     "samples/processing_app/basics/color/radial_gradient.rb",
     "samples/processing_app/basics/color/reading/data/cait.jpg",
     "samples/processing_app/basics/color/reading/reading.rb",
     "samples/processing_app/basics/color/relativity.rb",
     "samples/processing_app/basics/color/saturation.rb",
     "samples/processing_app/basics/color/wave_gradient.rb",
     "samples/processing_app/basics/control/conditionals1.rb",
     "samples/processing_app/basics/control/conditionals2.rb",
     "samples/processing_app/basics/control/embedded_iteration.rb",
     "samples/processing_app/basics/control/iteration.rb",
     "samples/processing_app/basics/control/logical_operators.rb",
     "samples/processing_app/basics/data/characters_strings/characters_strings.rb",
     "samples/processing_app/basics/data/characters_strings/data/Eureka-90.vlw",
     "samples/processing_app/basics/data/characters_strings/data/rathausFrog.jpg",
     "samples/processing_app/basics/data/datatype_conversion.rb",
     "samples/processing_app/basics/data/integers_floats.rb",
     "samples/processing_app/basics/data/true_false.rb",
     "samples/processing_app/basics/data/variable_scope.rb",
     "samples/processing_app/basics/data/variables.rb",
     "samples/processing_app/basics/form/bezier.rb",
     "samples/processing_app/basics/form/bezier_ellipse.rb",
     "samples/processing_app/basics/form/pie_chart.rb",
     "samples/processing_app/basics/form/points_lines.rb",
     "samples/processing_app/basics/form/shape_primitives.rb",
     "samples/processing_app/basics/form/triangle_strip.rb",
     "samples/processing_app/basics/form/vertices.rb",
     "samples/processing_app/basics/image/alphamask.rb",
     "samples/processing_app/basics/image/background_image.rb",
     "samples/processing_app/basics/image/create_image.rb",
     "samples/processing_app/basics/image/data/construct.jpg",
     "samples/processing_app/basics/image/data/eames.jpg",
     "samples/processing_app/basics/image/data/jelly.jpg",
     "samples/processing_app/basics/image/data/mask.jpg",
     "samples/processing_app/basics/image/data/milan_rubbish.jpg",
     "samples/processing_app/basics/image/data/teddy.gif",
     "samples/processing_app/basics/image/data/test.jpg",
     "samples/processing_app/basics/image/data/wash.jpg",
     "samples/processing_app/basics/image/load_display_image.rb",
     "samples/processing_app/basics/image/pointillism.rb",
     "samples/processing_app/basics/image/request_image.rb",
     "samples/processing_app/basics/image/sprite.rb",
     "samples/processing_app/basics/image/transparency.rb",
     "samples/processing_app/basics/input/clock.rb",
     "samples/processing_app/basics/input/constrain.rb",
     "samples/processing_app/basics/input/easing.rb",
     "samples/processing_app/basics/input/keyboard.rb",
     "samples/processing_app/basics/input/keyboard_2.rb",
     "samples/processing_app/basics/input/keyboard_functions.rb",
     "samples/processing_app/basics/input/milliseconds.rb",
     "samples/processing_app/basics/input/mouse_1d.rb",
     "samples/processing_app/basics/input/mouse_2d.rb",
     "samples/processing_app/basics/input/mouse_functions.rb",
     "samples/processing_app/basics/input/mouse_press.rb",
     "samples/processing_app/basics/input/mouse_signals.rb",
     "samples/processing_app/basics/input/storing_input.rb",
     "samples/processing_app/basics/math/additive_wave.rb",
     "samples/processing_app/basics/math/arctangent.rb",
     "samples/processing_app/topics/effects/data/red_smoke.jpg",
     "samples/processing_app/topics/effects/lens.rb",
     "samples/processing_app/topics/simulate/chain.rb",
     "samples/processing_app/topics/simulate/multiple_particle_systems.rb",
     "samples/processing_app/topics/simulate/simple_particle_system.rb",
     "samples/processing_app/topics/simulate/spring.rb",
     "samples/processing_app/topics/simulate/springs.rb",
     "samples/reflection.rb",
     "samples/simple_buffer.rb",
     "samples/tree.rb",
     "tasks/redis.rake",
     "tasks/resque.rake",
     "test-failures/dump.rdb",
     "test-failures/fail.rb",
     "test-failures/test-failures.conf",
     "test/redis-test.conf",
     "test/redis-test.pid",
     "test/resque_test.rb",
     "test/test_helper.rb",
     "test/worker_test.rb",
     "vendor/csp/README.markdown",
     "vendor/csp/examples/chatserver.ru",
     "vendor/csp/examples/echoserver.ru",
     "vendor/csp/examples/env.ru",
     "vendor/csp/examples/orbited.ru",
     "vendor/csp/lib/csp.rb",
     "vendor/csp/lib/csp/application.rb",
     "vendor/csp/lib/csp/async_body.rb",
     "vendor/csp/lib/csp/async_request.rb",
     "vendor/csp/lib/csp/packet.rb",
     "vendor/csp/lib/csp/session.rb",
     "vendor/csp/lib/static/csp.js",
     "vendor/csp/lib/static/echotest.html",
     "vendor/csp/lib/static/jquery.js"
  ]
  s.homepage = %q{http://github.com/defunkt/resque}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{}
  s.test_files = [
    "test/resque_test.rb",
     "test/test_helper.rb",
     "test/worker_test.rb",
     "examples/async_helper.rb",
     "examples/demo/app.rb",
     "examples/demo/job.rb",
     "examples/instance.rb",
     "examples/simple.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<redis-namespace>, [">= 0"])
      s.add_runtime_dependency(%q<vegas>, [">= 0.1.2"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<redis-namespace>, [">= 0"])
      s.add_dependency(%q<vegas>, [">= 0.1.2"])
      s.add_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<redis-namespace>, [">= 0"])
    s.add_dependency(%q<vegas>, [">= 0.1.2"])
    s.add_dependency(%q<sinatra>, [">= 0.9.2"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

